### ISSUE TITLE
[Bug]: Does not work in v-if

### ISSUE THREAD

**Issue by gregory-h** [grammarly/grammarly-for-developers#16]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk-vue

### SDK version

1.2.3

### Browser(s)

Chrome

### Steps to reproduce

Minimal Repro: (https://codesandbox.io/s/hardcore-knuth-lqbdg)

1. Open the sandbox
2. Click the textarea. Note that the grammarly indicator shows (bottom right) and the textarea grammarly functionality works
3. Click 'Toggle View' once to hide the textarea, and again to show the textarea 
4. Click the textarea. Note that the grammarly indicator does not show and the textarea grammarly functionality does not work.

### What happened?

Grammarly textarea works the first time the Grammarly component is rendered, but not after being removed and then re-inserted into the dom via a conditional (v-if) on an enclosing div

### What did you expect to happen?

Expect that the Grammarly component will function after being removed and then reinserted into the DOM, as will happen when it is used on a page that is conditionally rendered by a v-if attribute or used within a block associated with a :key attribute. 

### Contact Details

greg@lately.ai

**Comment by wachunga** [comment]
Thanks for the bug report! The team is mostly off over the holidays but we'll investigate as soon as possible.

**Comment by wachunga** [comment]
Fixed in [1.3.0](https://developer.grammarly.com/docs/changelog/#_1-3-0-2022-01-11). Please try it out.
