### ISSUE TITLE
[Bug]: `addPlugin` can make button spin infinitely

### ISSUE THREAD

**Issue by EtienneLem** [grammarly/grammarly-for-developers#197]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk

### SDK version

2.0.2

### Browser(s)

Chrome

### Operating system(s)

macOS

### Steps to reproduce

Minimal Repro: [CodeSandbox](https://codesandbox.io/s/grammarly-infinite-loading-forked-tlu3kq?file=/src/Editors.js)

1. Click **Page 2**
2. While button is still spinning, click **Page 1**
3. Button will spin forever

Note that while React has been used to simulate the navigation, the React SDK isn’t being used. Real world context is a React app with an older React version not supported by `@grammarly/editor-sdk-react`. Hence the manual `addPlugin` and `disconnect`.

In the example I’m using `activation: "immediate"` to make it easier to reproduce, but it’s the same result with `activation: "focus"`.

### What happened?

Grammarly button appears to be spinning forever

### What did you expect to happen?

Grammarly button should stop spinning. In the case of `activation: "immediate"` I’m assuming a short spin is expected, but in the case of `activation: "focus"`, no spin would be expected.

**Comment by AndrewDiMola** [comment]
Hey @EtienneLem, thanks for reporting this bug and for including your sandbox! I was able to reproduce the Grammarly button spinning indefinitely for both `activation: "immediate"` and `activation: "focus"` when I switched pages. 

I've let the team know and we'll keep you updated!

**Comment by kunalsinghal** [comment]
@EtienneLem we have a fix ready for this. It should go out in the next release. Thanks for spotting this -- Good catch!

**Comment by EtienneLem** [comment]
@kunalsinghal Amazing, thanks! 🤘🏼

**Comment by AndrewDiMola** [comment]
Hello again @EtienneLem, we just released a fix for this issue in our latest patch release: https://developer.grammarly.com/docs/changelog/#_2-0-3-2022-10-12

Because you're already on `2.0.x`, there shouldn't be any work required on your part. 

And please let us know if this bug is no longer an issue on your end!

**Comment by EtienneLem** [comment]
Thanks @AndrewDiMola. This issue seems to be gone, but unfortunately a new one arise I’m afraid. Still with the same [CodeSandbox](https://codesandbox.io/s/grammarly-infinite-loading-forked-tlu3kq?file=/src/Editors.js):

1. Click **Page 2**
2. Type something in the textarea with a typo, for example `my houuse is on fire.`
3. Click **Page 1**
4. Grammarly button stays in the “2 suggestions” state forever.

**Comment by AndrewDiMola** [comment]
> Thanks @AndrewDiMola. This issue seems to be gone, but unfortunately a new one arise I’m afraid. Still with the same [CodeSandbox](https://codesandbox.io/s/grammarly-infinite-loading-forked-tlu3kq?file=/src/Editors.js):
> 
> 1. Click **Page 2**
> 2. Type something in the textarea with a typo, for example `my houuse is on fire.`
> 3. Click **Page 1**
> 4. Grammarly button stays in the “2 suggestions” state forever.

Yes, I see the same thing. Thanks for the detailed instructions. 

Let me pass this on to the team and see if this is an already known issue.

**Comment by AndrewDiMola** [comment]
@EtienneLem - Confirmed that this is a novel bug. Thanks for surfacing! 

We have a fix that should keep the suggestions in sync with the editors and expect it to be a part of next week's release. I'll tag you then.

**Comment by EtienneLem** [comment]
Works great, thank you!
