### ISSUE TITLE
[Bug]: Running inside an iFrame Invalid Base URL (null Origin error)

### ISSUE THREAD

**Issue by asnewman** [grammarly/grammarly-for-developers#204]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk-react

### SDK version

2.0.2

### Operating system(s)

macOS

### Steps to reproduce

Use `<GrammarlyEditorPlugin>` within a Figma Plugin.

### What happened?

A bit niche scenario... I'm getting `index.esm.js:17 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid base URL`. This is happening inside a [Figma Plugin](https://www.figma.com/plugin-docs/) which runs React code within an iframe. Is there anything preventing the Grammarly SDK from running within an iFrame?

Update:
I did a little digging and I believe this issue is cause because `window.location.origin` is set to "null" within the iframe. I'm wondering if there is a workaround for this.

For reference, this is what the `window.location` object looks like:
```
{
    "ancestorOrigins": {
        "0": "https://www.figma.com",
        "1": "https://www.figma.com"
    },
    "href": "data:text/html;base64,PHNjcmlwdD4KICAgI...",
    "origin": "null",
    "protocol": "data:",
    "host": "",
    "hostname": "",
    "port": "",
    "pathname": "text/html;base64,PHNjcmlwdD4KICAgI...",
    "search": "",
    "hash": ""
}
```

### What did you expect to happen?

Loads normally.

**Comment by ljhaywar** [comment]
Welcome to the Grammarly for Developers community, @asnewman! And thanks for taking the time to report this issue!

The SDK works inside iframes. Here is a link to documentation about how to use the SDK with TinyMCE, which uses an iframe: https://developer.grammarly.com/docs/editor-sdk-intro#using-the-grammarly-editor-plugin-web-component. 

The null origin could be the problem. The SDK requires you to set the allowed origins for your app: https://developer.grammarly.com/docs/quick-start#origins-web-clients. I'm going to check with our engineering team to see if they have any suggestions.

In the meantime, do you have a running example we can take a look at? Or can you share a code snippet of how you're using <GrammarlyEditorPlugin>?

**Comment by asnewman** [comment]
Thanks for the response @ljhaywar! The code snippet is very straightforward, just:
```
<GrammarlyEditorPlugin clientId="my client ID">
    <textarea />
</GrammarlyEditorPlugin>
```

However, based on what you said, I was able to get it working! I added "null" to the allowed origins within my app in Grammarly and everything is working as expected. I'm not sure if this is the best in terms of security, though.

**Comment by ljhaywar** [comment]
Thanks for the update! I'll check with the team.

**Comment by ljhaywar** [comment]
Hi @asnewman - We released [version 2.0.3](https://developer.grammarly.com/docs/changelog/#_2-0-3-2022-10-12) yesterday. This version allows you to embed inside an iframe. If the iframe is sandboxed (we think Figma's plugin API may enforce this), then the embedding will still fail. Version 2.0.3 also contains an update to make the error message more helpful, so you may see a different error message. Let us know if using version 2.0.3 or using a non-null origin iframe fixes the issue. :-)

**Comment by asnewman** [comment]
Hey @ljhaywar I can confirm that my plugin is now getting the expected `Grammarly is not supported in IFrames with `null` origin.` message. I think you are correct in Figma forcing the iFrame to be sandboxed. I found this note on https://www.figma.com/plugin-docs/making-network-requests/: 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/15795866/195654800-0fb4da34-d831-422d-a59c-a03dc38a325d.png">

I just tried the non-null origin iFrame method with a basic create-react-app app, and it looks like it works! Unfortunately, moving my work's (https://dittowords.com) plugin repository to use this method won't be trivial, so if you or the team can come up with any other workarounds that would be much appreciated!

P.S. Fun launch party 🥳 I am tuning in from Twitch!

**Comment by ljhaywar** [comment]
Hi @asnewman! I'm happy to hear that the error message is working as expected and that the non-null origin iFrame method worked! That's disappointing that it will be a big lift to make this change in your repo. I talked with our team, and, unfortunately, we don't have any workarounds at this time. 

I'm so glad you were able to join the launch party! 🥳 I hope to see you again at our future events!

**Comment by AndrewDiMola** [comment]
Hello @asnewman! Thanks for joining the live stream the other day! Hopefully, you heard my callout!

Because we have a workaround, per https://github.com/grammarly/grammarly-for-developers/issues/204#issuecomment-1277452798, the non-null origin iFrame method, I'm going to close this issue. If you disagree, please feel free to reopen, create a new issue, or [start a discussion for a new idea](https://github.com/grammarly/grammarly-for-developers/discussions/new).

Thanks!
