### ISSUE TITLE
TypeError: e._p is not a function

### ISSUE THREAD

**Issue by znck** [grammarly/grammarly-for-developers#233]
### Discussed in https://github.com/grammarly/grammarly-for-developers/discussions/231

<div type='discussions-op-text'>

<sup>Originally posted by **andyvig** October 20, 2022</sup>
I tried mimicking the the Vue2 example here in my app: https://www.npmjs.com/package/@grammarly/editor-sdk-vue
And I get the following error in Chrome.  I'm on an older version of Vue2, is there minimum supported?
Any other ideas why I might be getting this error?  I just installed the Grammarly dependency so should have latest: "@grammarly/editor-sdk-vue": "^2.0.5",

`[Vue warn]: Error in created hook: "TypeError: e._p is not a function"`
`TypeError: e._p is not a function`

![image](https://user-images.githubusercontent.com/9019233/197064245-1df4b370-1309-49cc-a158-bee1ef04d87b.png)

```<script>
import { Grammarly, GrammarlyEditorPlugin } from "@grammarly/editor-sdk-vue/v2";

export default {
  data: () => ({  }),
  components: { Grammarly, GrammarlyEditorPlugin },
};
</script>

<template>
  <Grammarly clientId="MyClientIdHere">
    <div>
      <h2>Textarea</h2>
      <GrammarlyEditorPlugin>
        <textarea rows="10"></textarea>
      </GrammarlyEditorPlugin>

    </div>
  </Grammarly>
</template>```</div>

**Comment by andyvig** [comment]
Issue is fixed in 2.0.6

**Comment by AndrewDiMola** [comment]
Thanks for following up! 

Yes, fixed per https://github.com/grammarly/grammarly-for-developers/discussions/231#discussioncomment-3956270.

**Comment by AndrewDiMola** [comment]
@andyvig - I'm still investigating the issue with `matchMedia` returning `true` and `false` depending on the dock setup. If you want to create another issue, please do; otherwise I will after it's been confirmed.
