### ISSUE TITLE
[Bug]: Unable to accept any grammarly suggestion 

### ISSUE THREAD

**Issue by gregory-h** [grammarly/grammarly-for-developers#25]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk-vue

### SDK version

1.3.0 and 1.6.2

### Browser(s)

Chrome

### Operating system(s)

Linux

### Steps to reproduce

Minimal Repro: (https://codesandbox.io/s/github/grammarly/grammarly-for-developers/tree/main/examples/editor-sdk?file=/public/index.html)

1. Open the sandbox
2. Click on the first textarea, wait for grammarly to initialize and highlight issues in the text 
3. Hover on a grammarly highlighted error until popup with suggestions appears
4. Select 'Accept' on the popup, console throws error Invalid Constructor and editor text is not updated. 

### What happened?

Accepting any grammarly suggestion via the popup dialog is throwing an error and leaving the text unmodified

### What did you expect to happen?

Accepting a suggestion should modify the text

### Contact Details

greg@lately.ai

**Comment by gregory-h** [comment]
Interesting. 

I do *not* see this problem when using Firefox. 
If I open the referenced example sandbox in Chrome, I do see the problem and get the following stack trace. 
Based on the stacktrace it looks like the example sandbox is finding the 1.3 sdk? 

grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17 Uncaught (in promise) TypeError: Illegal constructor
    at grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
    at $S.applyAlertReplacement (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at onApply (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at notify (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
    at t.<anonymous> (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
    at Object.next (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
    at new Promise (<anonymous>)
    at Xn (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
    at _onClick (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at Object.ci (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at r (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
    at i (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at Lo (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at W (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at G (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at Q (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at Qi (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at g (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at he (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at fe (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at unstable_runWithPriority (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at St (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at Ki (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
    at le (grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17)
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
applyAlertReplacement @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
onApply @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
notify @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Xn @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
_onClick @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
ci @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
r @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
i @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Lo @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
W @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
G @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Q @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Qi @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
g @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
he @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
fe @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
unstable_runWithPriority @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
St @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Ki @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
le @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
async function (async)
onApply @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
notify @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Xn @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
_onClick @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
ci @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
r @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
(anonymous) @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
i @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Lo @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
W @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
G @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Q @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Qi @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
g @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
he @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
fe @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
unstable_runWithPriority @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
St @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
Ki @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17
le @ grammarly-editor-sdk@1.3?clientId=5c891c34-55b1-4504-b1a2-5215d35757ba:17

Grammarly.printLogs()
VM447:1 Uncaught ReferenceError: Grammarly is not defined
    at <anonymous>:1:1
(anonymous) @ VM447:1



We are currently using v1.3 of your lib in our app and I see the same issue with a slightly different stack trace after choosing 'Accept' in your dialog, 

Uncaught (in promise) TypeError: Illegal constructor
    at grammarly-editor-sdk@1.3:17
    at $S.applyAlertReplacement (grammarly-editor-sdk@1.3:17)
    at onApply (grammarly-editor-sdk@1.3:17)
    at notify (grammarly-editor-sdk@1.3:17)
    at grammarly-editor-sdk@1.3:17
    at t.<anonymous> (grammarly-editor-sdk@1.3:17)
    at grammarly-editor-sdk@1.3:17
    at Object.next (grammarly-editor-sdk@1.3:17)
    at grammarly-editor-sdk@1.3:17
    at new Promise (<anonymous>)

We have a couple of developers noticing the issue in our app and in your example sandbox.

**Comment by wachunga** [comment]
Sorry about the stale demos - I just bumped them to the latest version.

We're having trouble narrowing the issue down, and can't repro ourselves unfortunately.

Can you try upgrading to 1.6.2 and send us a stack trace from there? From the 1.3 stack trace you provided, there's `applyAlertReplacement` which constructs only expected browser things like InputEvent. 

A few questions we have:
- is this happening in a textarea or some other editor?
- which versions of Chrome and Linux are you using? 

A recording of some kind might also be helpful.
