### ISSUE TITLE
[Bug]: `addPlugin` only works once in 2.1.0

### ISSUE THREAD

**Issue by EtienneLem** [grammarly/grammarly-for-developers#278]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk

### SDK version

2.1.0

### Browser(s)

Chrome

### Operating system(s)

macOS

### Steps to reproduce

Minimal Repro: [CodeSandbox](https://codesandbox.io/s/grammarly-button-tlu3kq?file=/src/Editors.js)

1. Click **Page 2**
2. Grammarly buttons never reappears

### What happened?

When inspecting, the `<grammarly-button>` element is there, but the shadow root is empty:

<img width="726" alt="Screenshot 2022-11-07 at 4 09 57 PM" src="https://user-images.githubusercontent.com/436043/200416117-483aa059-5b7a-47ad-97f8-c185aa8c42af.png">

### What did you expect to happen?

The Grammarly button should reappear when calling `grammarly.addPlugin` again.

**Comment by AndrewDiMola** [comment]
Hello again! I checked your demo against `2.0.6` and `2.1.0` and noticed the same thing - that the Grammarly button does not appear on page 2. I'll bring this up to the team to confirm that is indeed a regression.

**Comment by EtienneLem** [comment]
> I checked your demo against `2.0.6` and `2.1.0` and noticed the same thing

FWIW; From what I can see, a reload is required on CodeSandbox after changing the version in order for it to take effect.

**Comment by jasonsperske** [comment]
We think we have a fix for this and are testing it right now, I'll report back here when this fix is scheduled for release.

**Comment by EtienneLem** [comment]
Fixed in [2.2.0](https://developer.grammarly.com/docs/changelog/#_2-2-0-2022-11-10), thank you!
