### ISSUE TITLE
[Bug]: Incorrect popover placement

### ISSUE THREAD

**Issue by simonpacis** [grammarly/grammarly-for-developers#295]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk

### SDK version

2.2.0

### Browser(s)

Chrome

### Operating system(s)

macOS

### Steps to reproduce

Minimal Repro: 

1. Download and install Obsidian (Electron app): [https://obsidian.md](https://obsidian.md)
2. Install Obsidian Grammarly Plugin: [https://github.com/simonpacis/obsidian-grammarly-plugin](https://github.com/simonpacis/obsidian-grammarly-plugin)
3. Enable plugin according to repository instructions
4. Popover is incorrectly placed

### What happened?

When the popover appears in Obsidian it is incorrectly placed. How is the popover placement calculated and is there anything we can do to place it correctly? See screenshot.

<img width="1680" alt="Screen Shot 2022-11-11 at 5 49 11 PM" src="https://user-images.githubusercontent.com/7118482/201389953-c5ad499a-7a4b-4e14-af66-b473c2f51fb2.png">

### What did you expect to happen?

That the popover was placed correctly according to the text.

**Comment by AndrewDiMola** [comment]
Hey @simonpacis. Great to see the progress on this plugin.

We just launched a [new troubleshooting page](https://developer.grammarly.com/docs/troubleshooting#suggestion-cards-are-covered-or-positioned-wrong) that includes guidance for when the suggestion card is incorrectly positioned.

Do you mind first checking the styling rules and their application relative to `<grammarly-editor-plugin>`?

An excerpt:
> *If suggestion cards are appearing in the wrong positions, or occluded by other elements, check the element for `position: absolute;` or `position: fixed;` style rules, and/or check if the element includes a `transform`. For these fixed positioning rules, we recommend moving these rules to a parent element—a parent element of both the Grammarly Text Editor Plugin and editor of your text editor framework.*

**Comment by simonpacis** [comment]
Hi Andrew,

Thank you, I must've missed the troubleshooting page. I'll give all of this a whirl and come back here if it still doesn't work.

All the best,
Simon
