### ISSUE TITLE
[Bug]: Spacing issues with content-editable=false/data-grammarly-skip

### ISSUE THREAD

**Issue by AndrewDiMola** [grammarly/grammarly-for-developers#310]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk

### SDK version

2.1.0

### Browser(s)

Chrome

### Operating system(s)

macOS

### Steps to reproduce

Created from a [community discussion](https://github.com/grammarly/grammarly-for-developers/discussions/307) by @asnewman. 

Reproduced here: https://codesandbox.io/s/cool-matsumoto-yl11fg?file=/public/index.html

### What happened?

> Suppose we have the following HTML:

```
<p>
   Hello <span content-editable="false">big</span> world.
</p>
```

> Grammarly sees this as "Hello--world" (two spaces between the word) and the suggestion will result in "big" getting deleted. I'm wondering how to avoid this from happening without doing something awkward like including one of the spaces in the "big" span.

> The use case here is that "big" is a variable that the user doesn't directly modify, but instead can change for other options like "small" or "tiny". As a result, I don't want the user or grammarly to be able to edit the text (thus it has `content-editable=false`).

![image](https://user-images.githubusercontent.com/5179225/202827078-74dd807b-b715-496a-a993-fc3bd92888a6.png)

### What did you expect to happen?

When using `data-grammarly-skip` and instances of `content-editable=false`, Grammarly and the Text Editor Plugin should be more cognizant of the spacing issues created from using these elements that skip words / phrases / content.

**Comment by wachunga** [comment]
Quick update here: we fixed the spacing issue in [2.2.1](https://developer.grammarly.com/docs/changelog/#_2-2-1-2022-11-22). In the future, we'll try to create a more comprehensive solution that also avoids unnecessary capitalization when using `data-grammarly-skip`.

**Comment by AndrewDiMola** [comment]
@asnewman - can you take a look in `2.2.1` (or later) and see if this resolves the spacing issue? 

As @wachunga said, we're also actively working on more fixes related to how we help you represent and skip different types of text for the plugin.

**Comment by AndrewDiMola** [comment]
Hey @asnewman - I'm closing this issue because it's been a few days since we've heard back from you and because we've tested that this specific spacing issues has been fixed in the latest release. If you feel differently, please reopen or comment below. Thanks!

**Comment by asnewman** [comment]
Hi @AndrewDiMola! Sorry, I miss this thread. I can confirm that everything is working as expected on my side now. Thanks for the fix Grammarly team!
