### ISSUE TITLE
[Bug]: Suggestion card positioning breaks when within transformed parent

### ISSUE THREAD

**Issue by GoonTwo** [grammarly/grammarly-for-developers#32]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk, @grammarly/editor-sdk-react, @grammarly/editor-sdk-vue

### SDK version

1.6.4

### Browser(s)

Chrome

### Operating system(s)

macOS

### Steps to reproduce

Minimal Repro: https://codesandbox.io/s/grammarly-transform-yq3z60

1. Open link
2. Hover on word with grammarly suggestion

### What happened?

Suggestion card does not line up with word that is being selected/hovered

This is because elements with a transform property create a new containing element for `position: fixed` children

https://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform

from [W3](https://www.w3.org/TR/css-transforms-1/)

> For elements whose layout is governed by the CSS box model, any value other than none for the [transform](https://www.w3.org/TR/css-transforms-1/#propdef-transform) property also causes the element to establish a containing block for all descendants. Its padding box will be used to layout for all of its absolute-position descendants, fixed-position descendants, and descendant fixed background attachments.

### What did you expect to happen?

Expect suggestion card to position correctly next to selected/hovered word

### Contact Details

dwelstad@curated.com

**Comment by GoonTwo** [comment]
If this is expected I can probably fix this on my end by removing the transform property after the animation is done, but the Chrome extension seems to avoid this issue by rendering the Suggestion Cards at the top of the DOM tree

**Comment by ljhaywar** [comment]
Thanks so much for reporting this, @GoonTwo! 🙌

We've reproduced the issue. We'll let you know when we have a recommended workaround or a fix.

**Comment by ljhaywar** [comment]
@GoonTwo We released v1.6.7 yesterday, which has a fix for this issue. I checked out your code sandbox, and the cards now look lined up correctly to me. Please let us know If you're still seeing the issue. 😊
