### ISSUE TITLE
[Bug]: `app-region` breaking Electron window dragging

### ISSUE THREAD

**Issue by EtienneLem** [grammarly/grammarly-for-developers#497]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk

### SDK version

v2.3.9

### Operating system(s)

None

### Steps to reproduce

Minimal Repro: Download [Electron Fiddle](https://www.electronjs.org/fiddle) and load this Gist URL: https://gist.github.com/EtienneLem/ca81c94ead39efd0620ad2f0f3289011. Reproducible on macOS and Windows.

You don’t need to have a working `clientId`, loading the script is enough to reproduce the issue.

<img width="914" alt="SCR-20230220-kbl" src="https://user-images.githubusercontent.com/436043/220187993-e833a47c-49e2-4077-99e7-5892b459df0c.png">

Because `app-region` is forced to `none`, the presence of a `grammarly-editor-plugin-mirror` can potentially break a window drag on electron if the `<pre>` appears anywhere in a region that is expected to drag.

Nota bene: Contrary to about everything else, `app-region` is flat. It doesn’t matter if add you add an element with a greater z-index on top of a `app-region: none` element; it will always have precedence. If there’s an `app-region: none` anywhere underneath the cursor when clicking, drag will be prevented.

### What happened?

Can’t drag the window

### What did you expect to happen?

Window should be draggable

**Possible solutions:**

1. Unless there’s a reason that I might be missing, `app-region` probably never needs to be set on that `<pre>` element.
2. Make it possible to style the `<pre>` element. Bit of a last resort workaround if solution 1 can’t be done. Adding a `part` attribute to the `<pre>` element would allow developers to overwrite certain styles, even if in ShadowDOM. Comes with the risk of overwriting a style that would break the display of the error underlines.

**Comment by cwatkins** [comment]
Hey @EtienneLem, 

Thanks for reporting this issue and including your Gist. I was able to reproduce  `grammarly-editor-plugin-mirror` breaking window drag. I'll bring this up with the team and circle back when I have more information.

**Comment by cwatkins** [comment]
@EtienneLem, 

We have a fix ready for this, and it should go out in the next release. Thanks again for letting us know!

**Comment by cwatkins** [comment]
Hi @EtienneLem, 

Good news! This was fixed in our [2.3.10 patch release](https://developer.grammarly.com/docs/changelog/#_2-3-10-2023-03-07) ("Fix to allow window dragging in Electron applications").

Let me know if it's working on your side.

**Comment by EtienneLem** [comment]
Great, thanks for the follow up @cwatkins. I confirm this issue is fixed on our end 🎉
