### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aserputov** [grammarly/grammarly-for-developers#54]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk

### Browser(s)

Chrome, Safari

### Operating system(s)

macOS

### Steps to reproduce

Minimal Repro: 

1. Leave Grammarly website with `Untitled doc open` in Pin Tabs.(in the left corner of safari open tabs)
2. Wait for 2-3 hours 
3. Click on the tab, start typing and fixing the text -> in 5-10 seconds ->
4. ERROR, PLEASE RELOAD
5. You Reload, and all the fixes for the text and gone... :(

### What happened?

I explained above.

### What did you expect to happen?

Fix the text.

### Contact Details

serputoff@gmail.com

**Comment by aserputov** [comment]
Might be a solution: set some JS instructions to automatically reload window, every 1-2 hours

**Comment by aserputov** [comment]
@ljhaywar, I'm using Grammarly Editor(ex. https://app.grammarly.com/ddocs/1******)

**Comment by ljhaywar** [comment]
@aserputov We use this repository for tracking bugs related to [Grammarly for Developers](https://developer.grammarly.com/). The Grammarly Editor is a separate offering, so I've alerted our support team. They've reached out to you via email. 

I'm going to close this ticket. Please reach out if you haven't received an email from our support team.
