### ISSUE TITLE
[Bug]: Underline is in wrong position when Grammarly plugin is used for multiline MUI TextField with label

### ISSUE THREAD

**Issue by mikhail-fedosenko** [grammarly/grammarly-for-developers#583]
### What package(s) are you seeing the problem in?

@grammarly/editor-sdk-react

### SDK version

2.3.13

### Browser(s)

Chrome

### Operating system(s)

macOS

### Steps to reproduce

Minimal Repro: https://codesandbox.io/s/grammarly-underline-issue-in-textfield-oguhuo?file=/src/App.js

1. Open codesandbox.
2. Click 'Show textfield' button in the demo to reveal the textbox.
3. Type 'mistke' in the textbox.

---
If you remove label from TextField - the issue goes away.
If you set `defaultValue` to non-empty string - the issue goes away.
If you render TextField at once, without toggle - the issue goes away.
If I use `setEditor`, `setViewport` as follows, the issue goes away too:
```jsx
<GrammarlyEditorPlugin>
  {({ setEditor, setViewport }) => {
    const inputRef = useRef();

    useEffect(() => {
      setEditor(inputRef.current ?? null);
      setViewport(inputRef.current ?? null);
    }, [setEditor, setViewport]);

    return (
      <TextField
        inputRef={inputRef}
        multiline
        defaultValue={""}
        label="Label"
      />
    );
  }}
</GrammarlyEditorPlugin>
```

### What happened?

The underline goes above 'mistke' word.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1673511/230385754-e2199255-d7a2-43a7-8358-d7835ede5553.png">

### What did you expect to happen?

'mistke' is underlined.

**Comment by cwatkins** [comment]
Hi @mikhail-fedosenko, 

Thanks for reporting this issue and including a minimal example of the problem. I can reproduce the issue and your workarounds. I'll bring this up with the team and circle back when I have more information.

**Comment by cwatkins** [comment]
Hi @mikhail-fedosenko,

Thanks for your patience!

I spoke with the engineering team, and this behavior wouldn't qualify as a bug. Instead, it's [a scenario that requires that you manually set the viewport to sync the suggestion lines](https://developer.grammarly.com/docs/diagnosing-issues#underlines-are-not-syncing-with-text). In those cases, we recommend using `setEditor` and `setViewport`, as you've done in your example workaround. 

I'm going to close this issue for now, but if you're ever unable to get the suggestion lines aligned with the text even after using setEditor and setViewport, please let us know, and we'll look into it further.
